name: Openwrt Build Bot
on:
  push:
    branches:
    - master
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: Which version of SDK
    #     required: true
    #     default: 'snapshots'
    #     type: choice
    #     options:
    #       - snapshots
    #       - 22.03.2
    #       - 21.02.05

jobs:
  dist:
    name: Build Openwrt Package
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        url:
        # - https://downloads.openwrt.org/releases/22.03.0/targets/ipq806x/generic/openwrt-sdk-22.03.0-ipq806x-generic_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
        # - https://downloads.openwrt.org/releases/22.03.0/targets/ipq40xx/generic/openwrt-sdk-22.03.0-ipq40xx-generic_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
        # - https://downloads.openwrt.org/releases/22.03.0/targets/ramips/mt7621/openwrt-sdk-22.03.0-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        # - https://downloads.openwrt.org/releases/22.03.0/targets/ath79/generic/openwrt-sdk-22.03.0-ath79-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        # - https://downloads.openwrt.org/releases/22.03.0/targets/ath79/nand/openwrt-sdk-22.03.0-ath79-nand_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        # - https://downloads.openwrt.org/releases/22.03.2/targets/x86/64/openwrt-sdk-22.03.2-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        - https://downloads.immortalwrt.org/snapshots/targets/x86/64/immortalwrt-sdk-x86-64_gcc-11.3.0_musl.Linux-x86_64.tar.xz
        # - https://downloads.openwrt.org/releases/22.03.0/targets/rockchip/armv8/openwrt-sdk-22.03.0-rockchip-armv8_gcc-11.2.0_musl.Linux-x86_64.tar.xz
    steps:
    - uses: actions/checkout@master
    - name: Install requirements
      run: sudo apt install -y wget curl libev-dev libc-ares-dev libudns-dev libncurses-dev
    - name: Download Openwrt SDK
      id: download_sdk
      run: |
        SDK_NAME=$(basename ${{ matrix.url }})
        SDK_HOME=$(head -c -8 <<< $SDK_NAME)
        curl ${{ matrix.url }} | tar -xJ
        mv $SDK_HOME sdk/
        cp key-build sdk/
    - name: Download Packages
      id: install_feeds
      working-directory: sdk
      run: |
        # Clash
        git clone -b master https://github.com/vernesong/OpenClash package/openclash
        # mosdns
        git clone --depth=1 https://github.com/sbwml/luci-app-mosdns.git package/luci-app-mosdns
        git clone --depth=1 https://github.com/sbwml/v2ray-geodata package/v2ray-geodata
        rm -rf package/luci-app-mosdns/mosdns
        # My own packages
        git clone --depth=1 https://github.com/icyleaf/openwrt-packages package/icyleaf
        # Update and install feeds
        ./scripts/feeds update -a
        ./scripts/feeds install golang c-ares libev libopenssl libsodium mbedtls pcre libncursesw6
        # Remove old version packages (custom packages)
        rm -rf package/feed/packages/tailscale
    - name: Generate config
      working-directory: sdk
      run: |
        echo "sdk_branch=$(sed -n 's/.*targets\/\(\w*\)\/\(\w*\)\/.*/packages\/\1\/\2/p' <<< ${{ matrix.url }})" >> $GITHUB_ENV
        make defconfig
        cat .config
    - name: Compile
      id: compile
      working-directory: sdk
      run: |
        make -j$(nproc) || make -j1 V=sc
        # post-compile
    - name: Organize packages
      id: organize
      working-directory: sdk
      if: steps.compile.outcome == 'success'
      run: |
        mkdir public
        mv bin/packages/*/base/*.ipk public/
    - name: Upload
      uses: peaceiris/actions-gh-pages@v3
      if: steps.organize.outcome == 'success'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: ${{ env.sdk_branch }}
        enable_jekyll: true
