name: Openwrt Build Bot
on:
  push:
    branches:
    - master
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: Which version of SDK
    #     required: true
    #     default: 'snapshots'
    #     type: choice
    #     options:
    #       - snapshots
    #       - 22.03.2
    #       - 21.02.05

jobs:
  dist:
    name: Build Openwrt Package
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        url:
        # - https://downloads.openwrt.org/releases/22.03.0/targets/ipq806x/generic/openwrt-sdk-22.03.0-ipq806x-generic_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
        # - https://downloads.openwrt.org/releases/22.03.0/targets/ipq40xx/generic/openwrt-sdk-22.03.0-ipq40xx-generic_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz
        # - https://downloads.openwrt.org/releases/22.03.0/targets/ramips/mt7621/openwrt-sdk-22.03.0-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        # - https://downloads.openwrt.org/releases/22.03.0/targets/ath79/generic/openwrt-sdk-22.03.0-ath79-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        # - https://downloads.openwrt.org/releases/22.03.0/targets/ath79/nand/openwrt-sdk-22.03.0-ath79-nand_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        # - https://downloads.openwrt.org/releases/22.03.2/targets/x86/64/openwrt-sdk-22.03.2-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        - https://downloads.immortalwrt.org/snapshots/targets/x86/64/immortalwrt-sdk-x86-64_gcc-11.3.0_musl.Linux-x86_64.tar.xz
        # - https://downloads.openwrt.org/releases/22.03.0/targets/rockchip/armv8/openwrt-sdk-22.03.0-rockchip-armv8_gcc-11.2.0_musl.Linux-x86_64.tar.xz
    steps:
    - uses: actions/checkout@master
    - name: Install requirements
      run: sudo apt install -y wget curl libev-dev libc-ares-dev libudns-dev libncurses-dev
    - name: Download Openwrt SDK
      run: |
        SDK_NAME=$(basename ${{ matrix.url }})
        SDK_HOME=$(head -c -8 <<< $SDK_NAME)
        curl ${{ matrix.url }} | tar -xJ
        mv $SDK_HOME sdk/
        cp key-build sdk/
    - name: Download Packages
      working-directory: sdk
      run: |
        # Shadowsocks
        git clone -b master https://github.com/shadowsocks/luci-app-shadowsocks package/luci-app-shadowsocks
        git clone -b master https://github.com/shadowsocks/openwrt-shadowsocks package/shadowsocks-libev
        git clone -b master https://github.com/aa65535/openwrt-simple-obfs package/simple-obfs
        # Misc
        git clone -b master https://github.com/aa65535/openwrt-chinadns package/chinadns
        git clone -b master https://github.com/aa65535/openwrt-dns-forwarder package/dns-forwarder
        git clone -b master https://github.com/aa65535/openwrt-dist-luci package/openwrt-dist-luci
        # Vlmcsd
        git clone -b master https://github.com/mchome/openwrt-vlmcsd package/vlmcsd
        git clone -b master https://github.com/mchome/luci-app-vlmcsd package/luci-app-vlmcsd
        # Clash
        git clone -b master https://github.com/vernesong/OpenClash package/openclash
        # Smartdns
        git clone -b master https://github.com/pymumu/openwrt-smartdns package/smartdns
        git clone -b master https://github.com/pymumu/luci-app-smartdns package/luci-app-smartdns
        sed -i 's|../../luci.mk|$(TOPDIR)/feeds/luci/luci.mk|g; 7iPKG_NAME:=luci-app-smartdns' package/luci-app-smartdns/Makefile
        # Dependency
        #git clone -b master https://github.com/shadowsocks/openwrt-feeds package/custom
        pushd package/openwrt-dist-luci/tools/po2lmo ; make && sudo make install ; popd
        ./scripts/feeds update -a
        ./scripts/feeds install golang c-ares libev libopenssl libsodium mbedtls pcre libncursesw6
    - name: Compile
      working-directory: sdk
      run: |
        make defconfig
        # Edit config
        make V=s
        echo "sdk_branch=$(sed -n 's/.*targets\/\(\w*\)\/\(\w*\)\/.*/packages\/\1\/\2/p' <<< ${{ matrix.url }})" >> $GITHUB_ENV

    - name: Upload
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./sdk/bin/packages/*/base
        publish_branch: ${{ env.sdk_branch }}

      # run: |
      #   TAG=$(sed -n 's/.*targets\/\(\w*\)\/\(\w*\)\/.*/packages\/\1\/\2/p' <<< ${{ matrix.url }})
      #   # Upload base only
      #   cd ~/sdk/bin/packages/*/base
      #   git init
      #   git config user.name "bot"
      #   git config user.email "bot@github.com"
      #   git add .
      #   git commit -m "$TAG$(TZ='Asia/Shanghai' date +@%Y%m%d)"
      #   git push --force --quiet "https://$GITHUB_TOKEN@github.com/simonsmh/openwrt-dist.git" HEAD:$TAG
